### ISSUE TITLE
Response Length Checking in Adventures

### ISSUE THREAD

**Issue by Alkali-Metal** [Adventurey-Things/Adventure-Bot#3]
The adventure command should check the character length of the `"description"` field to make sure that the bot can actually send it without any errors, ie, making sure it is >= 2000 characters long. If it is longer than 2000 characters long though, it should send a message to the chat saying that it encountered and error of some sort and what section of the adventure is too long. (Bonus points if it also alerts the `#development` channel in the Discord automatically)

**Comment by QuirkySquid** [comment]
Added.
